export const colors = {
    text: '#fff',
    textSecondary: '#ccc',
    textMuted: '#aaa',
    textSubtle: '#888',
    placeholder: '#666',
    background: '#1a1a1a',
    surface: '#2a2a2a',
    surfaceAlt: '#333',
    surfaceRaised: '#3a3a3a',
    surfaceInset: '#1e1e1e',
    border: '#444',
    primary: '#3498db',
    primaryDisabled: '#2c5f8a',
    danger: '#e74c3c',
    dangerSoft: '#ff6b6b',
    dangerStrong: '#ef4444',
    success: '#4CAF50',
} as const;
