import {
    createAbilityController,
    getAbilitiesController,
    editAbilityController,
    eraseAbilityController,
    createAdventureController,
    editAdventureController,
    getAdventuresController,
    appendChatAdventureController,
    createChatAdventureController,
    eraseAdventuresController,
    eraseAdventureController,
    getAdventureTextController,
    getAdventureSystemPromptController,
    hydrateAdventureController,
    startStreamingChatController,
    updateStreamingChatController,
    finishStreamingChatController,
    isAdventureStreamingController,
    createAssistantController,
    getAssistantsController,
    editAssistantController,
    eraseAssistantController,
    createCharacterController,
    getCharactersController,
    editCharacterController,
    eraseCharacterController,
    createConnectionConfigController,
    getConnectionsController,
    eraseConnectionController,
    editConnectionController,
    createItemController,
    getItemsController,
    editItemController,
    eraseItemController,
    createLocationController,
    getLocationsController,
    editLocationController,
    eraseLocationController,
    getModelsFromProviderController,
    createProficiencyController,
    getProficienciesController,
    editProficiencyController,
    eraseProficiencyController,
    createSamplerController,
    getSamplersController,
    editSamplerController,
    eraseSamplerController,
    createStatusController,
    getStatusesController,
    editStatusController,
    eraseStatusController,
    getStreamCompletionController,
    getNativeStreamCompletionController,
    createSystemPromptController,
    getSystemPromptsController,
    editSystemPromptController,
    eraseSystemPromptController,
    createWorldController,
    getWorldsController,
    eraseWorldController,
    editWorldController,
    createWorldMasterController,
    getWorldMasterController,
    editWorldMasterController,
    eraseWorldMasterController,
} from '@infra/container';
import type { AppControllers } from '@application/ui/providers/appControllers';

export function buildControllers (): AppControllers {
    return {

        createAbility: createAbilityController(),
        getAbilities: getAbilitiesController(),
        editAbility: editAbilityController(),
        eraseAbility: eraseAbilityController(),
        createAdventure: createAdventureController(),
        editAdventure: editAdventureController(),
        getAdventures: getAdventuresController(),
        appendChatAdventure: appendChatAdventureController(),
        createChatAdventure: createChatAdventureController(),
        eraseAdventures: eraseAdventuresController(),
        eraseAdventure: eraseAdventureController(),
        getAdventureText: getAdventureTextController(),
        getAdventureSystemPrompt: getAdventureSystemPromptController(),
        hydrateAdventure: hydrateAdventureController(),
        startStreamingChat: startStreamingChatController(),
        updateStreamingChat: updateStreamingChatController(),
        finishStreamingChat: finishStreamingChatController(),
        isAdventureStreaming: isAdventureStreamingController(),
        createAssistant: createAssistantController(),
        getAssistants: getAssistantsController(),
        editAssistant: editAssistantController(),
        eraseAssistant: eraseAssistantController(),
        createCharacter: createCharacterController(),
        getCharacters: getCharactersController(),
        editCharacter: editCharacterController(),
        eraseCharacter: eraseCharacterController(),
        createConnectionConfig: createConnectionConfigController(),
        getConnections: getConnectionsController(),
        eraseConnection: eraseConnectionController(),
        editConnection: editConnectionController(),
        createItem: createItemController(),
        getItems: getItemsController(),
        editItem: editItemController(),
        eraseItem: eraseItemController(),
        createLocation: createLocationController(),
        getLocations: getLocationsController(),
        editLocation: editLocationController(),
        eraseLocation: eraseLocationController(),
        getModelsFromProvider: getModelsFromProviderController(),
        createProficiency: createProficiencyController(),
        getProficiencies: getProficienciesController(),
        editProficiency: editProficiencyController(),
        eraseProficiency: eraseProficiencyController(),
        createSampler: createSamplerController(),
        getSamplers: getSamplersController(),
        editSampler: editSamplerController(),
        eraseSampler: eraseSamplerController(),
        createStatus: createStatusController(),
        getStatuses: getStatusesController(),
        editStatus: editStatusController(),
        eraseStatus: eraseStatusController(),
        getStreamCompletion: getStreamCompletionController(),
        getNativeStreamCompletion: getNativeStreamCompletionController(),
        createSystemPrompt: createSystemPromptController(),
        getSystemPrompts: getSystemPromptsController(),
        editSystemPrompt: editSystemPromptController(),
        eraseSystemPrompt: eraseSystemPromptController(),
        createWorld: createWorldController(),
        getWorlds: getWorldsController(),
        eraseWorld: eraseWorldController(),
        editWorld: editWorldController(),
        createWorldMaster: createWorldMasterController(),
        getWorldMasters: getWorldMasterController(),
        editWorldMaster: editWorldMasterController(),
        eraseWorldMaster: eraseWorldMasterController(),
    };
}
